services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: price_scrapper
    ports:
      - 5432:5432
  
  cookies:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
      - 4901:4901
      - 5901:5901
      - 6901:6901

  btc_scrapper:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        POSTGRES_CONN_STR: postgres://postgres:example@db:5432/price_scrapper
    ports:
      - 33987:33987
    depends_on:
      - db
      - cookies
