# syntax=docker/dockerfile:1
FROM python:3.13.5-bookworm

RUN mkdir -p /root/Code/cookie_monster

COPY . /root/Code/cookie_monster/

WORKDIR /root/Code/cookie_monster

RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        wget \
        gnupg \
        ca-certificates \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libxss1 \
        libxtst6 \
        libnss3 \
        libatk-bridge2.0-0 \
        libgtk-3-0 \
        x11-apps \
        fonts-liberation \
        libappindicator3-1 \
        libu2f-udev \
        libvulkan1 \
        libdrm2 \
        xdg-utils \
        xvfb \
        && rm -rf /var/lib/apt/lists/*

# Add Google Chrome repository and install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get update && \
    apt-get install -y google-chrome-stable

# Install Python dependencies
RUN pip install -r requirements.txt

# Define the command to run your application (example)
# CMD ["python3", "start.py --num_parallel 1 --base_port 8010"] 
CMD ["sleep", "infinity"] 

EXPOSE 8010